apiVersion: v1
kind: Service
metadata:
  name: dpp-monitor-service
spec:
  selector:
    app: dpp-monitor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort