apiVersion: v1
kind: Service # Tipo di risorsa creata
metadata:
  name: dpp-monitor-service # Nome del Service
spec:
  selector:
    app: dpp-monitor # Permette di selezionare i pod etichettati con app: dpp-monitor
  ports:
    - protocol: TCP # Protocollo TCP per la comunicazione
      port: 8000 # Porta su cui il Service è accessibile internamente al cluster
      targetPort: 8000 # Porta del contenitore su cui il traffico viene inviato
      nodePort: 30080 # Porta esposta all'esterno del cluster
  type: NodePort # Tipo di Service che permette l'accesso da fuori il cluster